version: '3'

services:
  chatgpt:
    container_name: chatgpt
    image: eryajf/chatgpt-dingtalk:latest
    restart: always
    environment:
      LOG_LEVEL: "info" # 应用的日志级别 info/debug
      BAIDU_CLIENT_ID: xxxxxx  # 你的百度应用ID
      BAIDU_CLIENT_SECRET: xxxxx # 你的百度应用key
      RUN_MODE: "stream"  # 运行模式，http 或者 stream ，强烈建议你使用stream模式，通过此链接了解：https://open.dingtalk.com/document/isvapp/stream
      DEFAULT_MODE: "单聊" # 指定默认的对话模式，可根据实际需求进行自定义，如果不设置，默认为单聊，即无上下文关联的对话模式
      MAX_REQUEST: 0 # 单人单日请求次数上限，默认为0，即不限制
      PORT: 8090 # 指定服务启动端口，默认为 8090，容器化部署时，不需要调整，一般在二进制宿主机部署时，遇到端口冲突时使用，如果run_mode为stream模式，则可以忽略该配置项
      CHAT_TYPE: "0" # 限定对话类型 0：不限 1：只能单聊 2：只能群聊
      ALLOW_GROUPS: "" # 哪些群组可以进行对话（仅在CHAT_TYPE为0、2时有效），如果留空，则表示允许所有群组，如果要限制，则列表中写群ID（ConversationID）
      # 群ID，可在群组中 @机器人 群ID 来查看日志获取，例如日志会输出：[🙋 企业内部机器人 在『测试』群的ConversationID为: "cidrabcdefgh1234567890AAAAA"]，获取后可填写该参数并重启程序
      # 如果不想支持outgoing机器人功能，这里可以随意设置一个内部群组，例如：cidrabcdefgh1234567890AAAAA；或随意一个字符串，例如：disabled
      # 建议该功能默认关闭：除非你必须要用到outgoing机器人
      ALLOW_OUTGOING_GROUPS: ""   # 哪些普通群（使用outgoing机器人）可以进行对话，如果留空，则表示允许所有群组，如果要限制，则列表中写群ID（ConversationID）
      # 以下 ALLOW_USERS、DENY_USERS、VIP_USERS、ADMIN_USERS 配置中填写的是用户的userid
      # 比如 ["1301691029702722","1301691029702733"]，这个信息需要在钉钉管理后台的通讯录当中获取：https://oa.dingtalk.com/contacts.htm#/contacts
      # 哪些用户可以进行对话，如果留空，则表示允许所有用户，如果要限制，则列表中写用户的userid
      ALLOW_USERS: "" # 哪些用户可以进行对话，如果留空，则表示允许所有用户，如果要限制，则填写用户的userid
      DENY_USERS: "" # 哪些用户不可以进行对话，如果留空，则表示允许所有用户（如allow_user有配置，需满足相应条件），如果要限制，则列表中写用户的userid，黑名单优先级高于白名单
      VIP_USERS: "" # 哪些用户可以进行无限对话，如果留空，则表示只允许管理员（如max_request配置为0，则允许所有人），如果要针对指定VIP用户放开限制（如max_request配置不为0），则列表中写用户的userid
      ADMIN_USERS: "" # 指定哪些人为此系统的管理员，如果留空，则表示没有人是管理员，如果要限制，则列表中写用户的userid
      # 注意：如果下边的app_secrets为空，以及使用outgoing的方式配置机器人，这两种情况下，都表示没有人是管理员
      APP_SECRETS: "" # 钉钉机器人在应用信息中的AppSecret，为了校验回调的请求是否合法，如果留空，将会忽略校验，则该接口将会存在其他人也能随意调用的安全隐患，因此强烈建议配置正确的secret，如果你的服务对接给多个机器人，这里可以配置多个机器人的secret，比如 "xxxx,yyyy"
      SENSITIVE_WORDS: "" # 敏感词，提问时触发，则不允许提问，回答的内容中触发，则以 🚫 代替
      DINGTALK_CREDENTIALS: "" # 钉钉应用访问凭证，比如 "client_id1:secret1,client_id2:secret2"
      HELP: "欢迎使用本工具\n\n你可以查看：[用户指南](https://github.com/ConnectAI-E/Dingtalk-Wenxin/blob/main/docs/userGuide.md)\n\n这是一个[开源项目](https://github.com/ConnectAI-E/Dingtalk-Wenxin/)，觉得不错你可以来波素质三连." # 帮助信息，放在配置文件，可供自定义
    volumes:
      - ./data:/app/data
    ports:
      - "8090:8090"